services:
  service-users:
    container_name: whatdoing-service-users
    build:
      context: ./services/users/
      dockerfile: Dockerfile
    image: service-user-app
    env_file: ./services/users/.env
    restart: unless-stopped
    networks:
      whatdoing-network:
        aliases:
          - auth-service

  service-anime:
    container_name: whatdoing-service-anime
    build:
      context: ./services/anime/
      dockerfile: Dockerfile
    command: ["--mode", "service", "--env", "prod"]
    image: service-anime-app
    env_file: ./services/anime/.env
    restart: unless-stopped
    networks:
      whatdoing-network:
        aliases:
          - anime-service

  service-anime-pub:
    container_name: whatdoing-service-anime-pub
    build:
      context: ./services/anime/
      dockerfile: Dockerfile
    command: ["--mode", "pub", "--env", "prod"]
    image: service-anime-app
    env_file: ./services/anime/.env
    restart: unless-stopped
    networks:
      - whatdoing-network

  service-progress:
    container_name: whatdoing-service-progress
    build:
      context: ./services/progress/
      dockerfile: Dockerfile
    command: ["--mode", "service", "--env", "prod"]
    image: service-anime-progress-app
    env_file: ./services/progress/.env
    restart: unless-stopped
    networks:
      whatdoing-network:
        aliases:
          - anime-progress

  service-progress-sub:
    container_name: whatdoing-service-progress-sub
    build:
      context: ./services/progress/
      dockerfile: Dockerfile
    command: ["--mode", "sub", "--env", "prod"]
    image: service-anime-progress-app
    env_file: ./services/progress/.env
    restart: unless-stopped
    networks:
      - whatdoing-network

networks:
  whatdoing-network:
    external: true
