# test databases
services:
  users_db:
    container_name: whatdoing-service-users-db
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - "./services/users/.database/pg-test-data:/var/lib/postgresql/data:rw"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d postgres'"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 15s
    networks:
      whatdoing-network:
        aliases:
          - auth-service-test-db

  anime_db:
    container_name: whatdoing-service-anime-db
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5433:5432"
    volumes:
      - "./services/anime/.database/pg-test-data:/var/lib/postgresql/data:rw"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d postgres'"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 15s
    networks:
      whatdoing-network:
        aliases:
          - anime-service-test-db

  progress_db:
    container_name: whatdoing-service-anime-progress-db
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - "./services/progress/.database/pg-test-data:/var/lib/postgresql/data:rw"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d postgres'"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 15s
    networks:
      whatdoing-network:
        aliases:
          - anime-progress-service-test-db

networks:
  whatdoing-network:
    external: true
