services:
  service-users:
    container_name: whatdoing-service-users
    build:
      context: ./services/users/
      dockerfile: Dockerfile
    image: service-user-app
    env_file: ./services/users/.env
    restart: unless-stopped
    networks:
      whatdoing-network:
        aliases:
          - auth-service

  service-anime:
    container_name: whatdoing-service-anime
    build:
      context: ./services/anime/
      dockerfile: Dockerfile
    command: ["service", "prod"]
    image: service-anime-app
    env_file: ./services/anime/.env
    restart: unless-stopped
    networks:
      whatdoing-network:
        aliases:
          - anime-service

  service-anime-pub:
    container_name: whatdoing-service-anime-pub
    build:
      context: ./services/anime/
      dockerfile: Dockerfile
    command: ["pub", "prod"]
    image: service-anime-app
    env_file: ./services/anime/.env
    restart: unless-stopped
    networks:
      - whatdoing-network

networks:
  whatdoing-network:
    external: true
